---
title: "<span style='color:#6E3778;'>Your First Launch of </span><span style='color:#008CA5;'>ATLAS</span><span style='color:#EBB400;'>²</span>"
---

Now, let's do our first launch of ATLAS² with sample from online repository. You will everything mentionned here inside the `test-files` folder from the `git clone` done before.

## Parameters file

First, you will need a parameter file `params.yml` to make your life easier. A parameter file is a `.yml` file containing any parameters with their value that you would want to give to the pipeline. It substitute to simply adding them one by one in the command line after Nextflow run command 

```bash
nextflow run main.nf -params-file params.yml
``` 
instead of 

```bash
nextflow run main.nf --params1 value1 --params2 value2 ..
```

Here is an example of parameters file, you will find the file to use at `test-files/params.yml`

```yaml
outdir: './result'  
workdir: './work' 
samplesheet: "./samplesheet.csv"
genome: null
sub_samplesheet: null
cpus: 4
memory: 16.GB

init: true
preprocess_only: true
skip_preprocess: false
```

## Samplesheet file

After creating your parameters file, you will need a samplesheet to tell the pipeline what are your samples' accession number. A first samplesheet that we will be using is 

```bash
accession,customs,extract,replace,stage
GSM9153248,,,,,
GSM9153249,,,,,
```
that you can find inside at `test-files/samplesheet.csv`
Those two WGBS sample from the paper [Preventing CpG hypermethylation in oocytes safeguards mouse development](https://pubmed.ncbi.nlm.nih.gov/40902605/).

A samplesheet is your way of telling the pipeline which samples you want to retrieve and how to identify them. A samplesheet has 5 columns : accession, customs, extract, replace and stage. For now we are only interested in the accession column. The samplesheet is only filled out with the accession number and you will run the pipeline with the argument `init: true` (by default) in your `params.yml` to do an `Initialization` step. 

With everything in hand we can launch a first run, go into the `params.yml` file and change the `samplesheet` parameter value to the path of your samplesheet then run the following command

```bash
nextflow run main.nf params-file params.yml

or

nextflow run path/to/pipeline/main.nf params-file params.yml
```

This first run will give an output with this tree structure 

```bash
├── params.yml
├── result
│   ├── fastqdl
│   │   └── metadata
│   │       ├── GSM9153248
│   │       │   └── fastq-run-info.tsv
│   │       └── GSM9153249
│   │           └── fastq-run-info.tsv
│   └── pipeline_info
│       ├── execution_dag_2026-09-22_10-27-32.html
│       ├── execution_report_2026-09-22_10-27-32.html
│       ├── execution_timeline_2026-09-22_10-27-32.html
│       └── execution_trace_2026-09-22_10-27-32.txt
└── samplesheet.csv
# and a work folder not shown here
```

Here you retrieved the metadata for those two sample and stored them inside `fastqdl/metadata/accession_number/fastq-run-info.tsv` you will find all type of columns inside this file and a first step would be to explore this file and find one or more column to use as a unique and informative identifier.

Here for example we will use two columns : experiment_title and run_accession. To tell that to the pipeline, you will add inside the samplesheet under the column `customs` the name of those columns separated by `$;$`

```bash
accession,customs,extract,replace,stage
GSM9153248,experiment_title$;$run_accession,,,,
GSM9153249,experiment_title$;$run_accession,,,,
```


::: {.d-flex .justify-content-between .mt-5}
[← Get started](../get_started/index.qmd){.fw-bold style="color: #6E3778; font-size: 20px;"}

[Usage →](../usage/index.qmd){.fw-bold style="color: #6E3778; font-size: 20px;"}
:::
